
# from groq import Groq
# from backend.config import GROQ_API_KEY

# client = Groq(api_key=GROQ_API_KEY)


# def call_llm(prompt: str) -> str:
#     try:
#         completion = client.chat.completions.create(
#             model="qwen/qwen3-32b",
#             messages=[
#                 {
#                     "role": "system",
#                     "content": (
#                         "You are an expert B2B sales closer and deal intelligence assistant. "
#                         "Use past interactions when relevant. "
#                         "Respond in a short, persuasive, professional way. "
#                         "Keep the response under 3 lines. "
#                         "Do not reveal reasoning. "
#                         "Do not output <think> tags or internal analysis."
#                     ),
#                 },
#                 {"role": "user", "content": prompt},
#             ],
#             temperature=0.7,
#         )

#         content = completion.choices[0].message.content
#         return content.strip() if content else "I understand the concern. Let’s align on the best next step."

#     except Exception as e:
#         print("LLM ERROR:", repr(e))
#         return f"LLM Error: {str(e)}"

"""
backend/llm.py

Purpose:
    This module handles all interactions with the Groq LLM.

What this file does:
    1. Initializes the Groq client using API key
    2. Sends prompts to the LLM
    3. Controls model behavior using system instructions
    4. Handles errors safely
    5. Returns clean, usable responses

Why this matters:
    This is the communication layer between your AI agent and the language model.
    It ensures responses are:
        - concise
        - persuasive
        - professional
        - aligned with sales use-case

Model used:
    - qwen/qwen3-32b (fast + good for structured reasoning tasks)
"""

from groq import Groq
from backend.config import GROQ_API_KEY


# -------------------------------------------------------------------
# Initialize Groq Client
# -------------------------------------------------------------------
# The client is created once and reused for all requests.
# This avoids re-initialization overhead.
client = Groq(api_key=GROQ_API_KEY)


# -------------------------------------------------------------------
# LLM Call Function (Core)
# -------------------------------------------------------------------

def call_llm(prompt: str) -> str:
    """
    Send a prompt to the Groq LLM and return the generated response.

    Args:
        prompt (str): The user prompt containing context, deal data,
                      and instructions generated by the agent.

    Returns:
        str: Clean LLM response (max ~2-3 lines).
             Returns fallback message if empty.
             Returns error message if request fails.

    Behavior:
        - Uses a system prompt to control tone and style
        - Keeps responses short and persuasive
        - Avoids reasoning output or hidden tags

    Why system prompt is important:
        It defines how the model should behave consistently
        across all conversations.

    Example:
        Input:
            "Client says it's too expensive"

        Output:
            "I understand your concern — many clients felt the same initially,
             but they saw strong ROI within months. Let’s walk through that together."
    """
    try:
        # ------------------------------------------------------------
        # Create chat completion request
        # ------------------------------------------------------------
        completion = client.chat.completions.create(

            # Model selection (fast + strong reasoning)
            model="qwen/qwen3-32b",

            # Conversation messages
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an expert B2B sales closer and deal intelligence assistant. "
                        "Use past interactions when relevant. "
                        "Respond in a short, persuasive, professional way. "
                        "Keep the response under 3 lines. "
                        "Do not reveal reasoning. "
                        "Do not output <think> tags or internal analysis."
                    ),
                },
                {
                    "role": "user",
                    "content": prompt
                },
            ],

            # Controls creativity vs determinism
            temperature=0.7,
        )

        # ------------------------------------------------------------
        # Extract response content safely
        # ------------------------------------------------------------
        content = completion.choices[0].message.content

        # Fallback response if model returns empty
        return (
            content.strip()
            if content
            else "I understand the concern. Let’s align on the best next step."
        )

    except Exception as e:
        # ------------------------------------------------------------
        # Error Handling
        # ------------------------------------------------------------
        # Print error for debugging (backend logs)
        print("LLM ERROR:", repr(e))

        # Return safe error message (prevents system crash)
        return f"LLM Error: {str(e)}"